/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedEducationIndexRouteImport } from './routes/_authenticated/education/index'
import { Route as AuthenticatedSettingsBusinessRouteImport } from './routes/_authenticated/settings/business'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedEducationModuleIdRouteImport } from './routes/_authenticated/education/$moduleId'
import { Route as AuthenticatedEducationModuleIdIndexRouteImport } from './routes/_authenticated/education/$moduleId/index'
import { Route as AuthenticatedEducationModuleIdLessonIdRouteImport } from './routes/_authenticated/education/$moduleId/$lessonId'
import { Route as AuthenticatedEducationModuleIdLessonIdIndexRouteImport } from './routes/_authenticated/education/$moduleId/$lessonId/index'
import { Route as AuthenticatedEducationModuleIdLessonIdPackIdRouteImport } from './routes/_authenticated/education/$moduleId/$lessonId/$packId'
import { Route as AuthenticatedEducationModuleIdLessonIdPackIdIndexRouteImport } from './routes/_authenticated/education/$moduleId/$lessonId/$packId/index'
import { Route as AuthenticatedEducationModuleIdLessonIdPackIdTopicRouteImport } from './routes/_authenticated/education/$moduleId/$lessonId/$packId/topic'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedEducationIndexRoute =
  AuthenticatedEducationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedSettingsBusinessRoute =
  AuthenticatedSettingsBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationModuleIdRoute =
  AuthenticatedEducationModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedEducationRoute,
  } as any)
const AuthenticatedEducationModuleIdIndexRoute =
  AuthenticatedEducationModuleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEducationModuleIdRoute,
  } as any)
const AuthenticatedEducationModuleIdLessonIdRoute =
  AuthenticatedEducationModuleIdLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedEducationModuleIdRoute,
  } as any)
const AuthenticatedEducationModuleIdLessonIdIndexRoute =
  AuthenticatedEducationModuleIdLessonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEducationModuleIdLessonIdRoute,
  } as any)
const AuthenticatedEducationModuleIdLessonIdPackIdRoute =
  AuthenticatedEducationModuleIdLessonIdPackIdRouteImport.update({
    id: '/$packId',
    path: '/$packId',
    getParentRoute: () => AuthenticatedEducationModuleIdLessonIdRoute,
  } as any)
const AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute =
  AuthenticatedEducationModuleIdLessonIdPackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEducationModuleIdLessonIdPackIdRoute,
  } as any)
const AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute =
  AuthenticatedEducationModuleIdLessonIdPackIdTopicRouteImport.update({
    id: '/topic',
    path: '/topic',
    getParentRoute: () => AuthenticatedEducationModuleIdLessonIdPackIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/education': typeof AuthenticatedEducationRouteWithChildren
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/education/$moduleId': typeof AuthenticatedEducationModuleIdRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/education/': typeof AuthenticatedEducationIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/education/$moduleId/$lessonId': typeof AuthenticatedEducationModuleIdLessonIdRouteWithChildren
  '/education/$moduleId/': typeof AuthenticatedEducationModuleIdIndexRoute
  '/education/$moduleId/$lessonId/$packId': typeof AuthenticatedEducationModuleIdLessonIdPackIdRouteWithChildren
  '/education/$moduleId/$lessonId/': typeof AuthenticatedEducationModuleIdLessonIdIndexRoute
  '/education/$moduleId/$lessonId/$packId/topic': typeof AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute
  '/education/$moduleId/$lessonId/$packId/': typeof AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/education': typeof AuthenticatedEducationIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/education/$moduleId': typeof AuthenticatedEducationModuleIdIndexRoute
  '/education/$moduleId/$lessonId': typeof AuthenticatedEducationModuleIdLessonIdIndexRoute
  '/education/$moduleId/$lessonId/$packId/topic': typeof AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute
  '/education/$moduleId/$lessonId/$packId': typeof AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/education': typeof AuthenticatedEducationRouteWithChildren
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/education/$moduleId': typeof AuthenticatedEducationModuleIdRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/_authenticated/education/': typeof AuthenticatedEducationIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/education/$moduleId/$lessonId': typeof AuthenticatedEducationModuleIdLessonIdRouteWithChildren
  '/_authenticated/education/$moduleId/': typeof AuthenticatedEducationModuleIdIndexRoute
  '/_authenticated/education/$moduleId/$lessonId/$packId': typeof AuthenticatedEducationModuleIdLessonIdPackIdRouteWithChildren
  '/_authenticated/education/$moduleId/$lessonId/': typeof AuthenticatedEducationModuleIdLessonIdIndexRoute
  '/_authenticated/education/$moduleId/$lessonId/$packId/topic': typeof AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute
  '/_authenticated/education/$moduleId/$lessonId/$packId/': typeof AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/education'
    | '/subscriptions'
    | '/'
    | '/education/$moduleId'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/business'
    | '/education/'
    | '/settings/'
    | '/users'
    | '/education/$moduleId/$lessonId'
    | '/education/$moduleId/'
    | '/education/$moduleId/$lessonId/$packId'
    | '/education/$moduleId/$lessonId/'
    | '/education/$moduleId/$lessonId/$packId/topic'
    | '/education/$moduleId/$lessonId/$packId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/subscriptions'
    | '/'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/business'
    | '/education'
    | '/settings'
    | '/users'
    | '/education/$moduleId'
    | '/education/$moduleId/$lessonId'
    | '/education/$moduleId/$lessonId/$packId/topic'
    | '/education/$moduleId/$lessonId/$packId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/education'
    | '/_authenticated/subscriptions'
    | '/_authenticated/'
    | '/_authenticated/education/$moduleId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/business'
    | '/_authenticated/education/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/education/$moduleId/$lessonId'
    | '/_authenticated/education/$moduleId/'
    | '/_authenticated/education/$moduleId/$lessonId/$packId'
    | '/_authenticated/education/$moduleId/$lessonId/'
    | '/_authenticated/education/$moduleId/$lessonId/$packId/topic'
    | '/_authenticated/education/$moduleId/$lessonId/$packId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/education/': {
      id: '/_authenticated/education/'
      path: '/'
      fullPath: '/education/'
      preLoaderRoute: typeof AuthenticatedEducationIndexRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/settings/business': {
      id: '/_authenticated/settings/business'
      path: '/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education/$moduleId': {
      id: '/_authenticated/education/$moduleId'
      path: '/$moduleId'
      fullPath: '/education/$moduleId'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdRouteImport
      parentRoute: typeof AuthenticatedEducationRoute
    }
    '/_authenticated/education/$moduleId/': {
      id: '/_authenticated/education/$moduleId/'
      path: '/'
      fullPath: '/education/$moduleId/'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdIndexRouteImport
      parentRoute: typeof AuthenticatedEducationModuleIdRoute
    }
    '/_authenticated/education/$moduleId/$lessonId': {
      id: '/_authenticated/education/$moduleId/$lessonId'
      path: '/$lessonId'
      fullPath: '/education/$moduleId/$lessonId'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedEducationModuleIdRoute
    }
    '/_authenticated/education/$moduleId/$lessonId/': {
      id: '/_authenticated/education/$moduleId/$lessonId/'
      path: '/'
      fullPath: '/education/$moduleId/$lessonId/'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdLessonIdIndexRouteImport
      parentRoute: typeof AuthenticatedEducationModuleIdLessonIdRoute
    }
    '/_authenticated/education/$moduleId/$lessonId/$packId': {
      id: '/_authenticated/education/$moduleId/$lessonId/$packId'
      path: '/$packId'
      fullPath: '/education/$moduleId/$lessonId/$packId'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdRouteImport
      parentRoute: typeof AuthenticatedEducationModuleIdLessonIdRoute
    }
    '/_authenticated/education/$moduleId/$lessonId/$packId/': {
      id: '/_authenticated/education/$moduleId/$lessonId/$packId/'
      path: '/'
      fullPath: '/education/$moduleId/$lessonId/$packId/'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdIndexRouteImport
      parentRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdRoute
    }
    '/_authenticated/education/$moduleId/$lessonId/$packId/topic': {
      id: '/_authenticated/education/$moduleId/$lessonId/$packId/topic'
      path: '/topic'
      fullPath: '/education/$moduleId/$lessonId/$packId/topic'
      preLoaderRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdTopicRouteImport
      parentRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBusinessRoute: typeof AuthenticatedSettingsBusinessRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBusinessRoute: AuthenticatedSettingsBusinessRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedEducationModuleIdLessonIdPackIdRouteChildren {
  AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute
  AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute
}

const AuthenticatedEducationModuleIdLessonIdPackIdRouteChildren: AuthenticatedEducationModuleIdLessonIdPackIdRouteChildren =
  {
    AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute:
      AuthenticatedEducationModuleIdLessonIdPackIdTopicRoute,
    AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute:
      AuthenticatedEducationModuleIdLessonIdPackIdIndexRoute,
  }

const AuthenticatedEducationModuleIdLessonIdPackIdRouteWithChildren =
  AuthenticatedEducationModuleIdLessonIdPackIdRoute._addFileChildren(
    AuthenticatedEducationModuleIdLessonIdPackIdRouteChildren,
  )

interface AuthenticatedEducationModuleIdLessonIdRouteChildren {
  AuthenticatedEducationModuleIdLessonIdPackIdRoute: typeof AuthenticatedEducationModuleIdLessonIdPackIdRouteWithChildren
  AuthenticatedEducationModuleIdLessonIdIndexRoute: typeof AuthenticatedEducationModuleIdLessonIdIndexRoute
}

const AuthenticatedEducationModuleIdLessonIdRouteChildren: AuthenticatedEducationModuleIdLessonIdRouteChildren =
  {
    AuthenticatedEducationModuleIdLessonIdPackIdRoute:
      AuthenticatedEducationModuleIdLessonIdPackIdRouteWithChildren,
    AuthenticatedEducationModuleIdLessonIdIndexRoute:
      AuthenticatedEducationModuleIdLessonIdIndexRoute,
  }

const AuthenticatedEducationModuleIdLessonIdRouteWithChildren =
  AuthenticatedEducationModuleIdLessonIdRoute._addFileChildren(
    AuthenticatedEducationModuleIdLessonIdRouteChildren,
  )

interface AuthenticatedEducationModuleIdRouteChildren {
  AuthenticatedEducationModuleIdLessonIdRoute: typeof AuthenticatedEducationModuleIdLessonIdRouteWithChildren
  AuthenticatedEducationModuleIdIndexRoute: typeof AuthenticatedEducationModuleIdIndexRoute
}

const AuthenticatedEducationModuleIdRouteChildren: AuthenticatedEducationModuleIdRouteChildren =
  {
    AuthenticatedEducationModuleIdLessonIdRoute:
      AuthenticatedEducationModuleIdLessonIdRouteWithChildren,
    AuthenticatedEducationModuleIdIndexRoute:
      AuthenticatedEducationModuleIdIndexRoute,
  }

const AuthenticatedEducationModuleIdRouteWithChildren =
  AuthenticatedEducationModuleIdRoute._addFileChildren(
    AuthenticatedEducationModuleIdRouteChildren,
  )

interface AuthenticatedEducationRouteChildren {
  AuthenticatedEducationModuleIdRoute: typeof AuthenticatedEducationModuleIdRouteWithChildren
  AuthenticatedEducationIndexRoute: typeof AuthenticatedEducationIndexRoute
}

const AuthenticatedEducationRouteChildren: AuthenticatedEducationRouteChildren =
  {
    AuthenticatedEducationModuleIdRoute:
      AuthenticatedEducationModuleIdRouteWithChildren,
    AuthenticatedEducationIndexRoute: AuthenticatedEducationIndexRoute,
  }

const AuthenticatedEducationRouteWithChildren =
  AuthenticatedEducationRoute._addFileChildren(
    AuthenticatedEducationRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRouteWithChildren
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedEducationRoute: AuthenticatedEducationRouteWithChildren,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
